/*
 * This source file was generated by the Gradle 'init' task
 */
package SolitaireSolver;

public class Foundation {
    int spades, hearts, clubs, diamonds;

    public Foundation() {
        spades = 0;
        hearts = 0;
        clubs = 0;
        diamonds = 0;
    }

    public boolean incrementSpades() {
        if (spades != 13) {
            spades += 1;
            return true;
        }
        return false;
    }

    public boolean incrementHearts() {
        if (hearts != 13) {
            hearts += 1;
            return true;
        }
        return false;
    }

    public boolean incrementClubs() {
        if (clubs != 13) {
            clubs += 1;
            return true;
        }
        return false;
    }

    public boolean incrementDiamonds() {
        if (diamonds != 13) {
            diamonds += 1;
            return true;
        }
        return false;
    }

    public int getSpades() {
        return spades;
    }

    public int getHearts() {
        return hearts;
    }

    public int getClubs() {
        return clubs;
    }

    public int getDiamonds() {
        return diamonds;
    }

    //Note: These getters are only to visualise the game. They will not be used in actual solution.
    //      Getters returning the integer values will be used instead.

    public String getSpadeCard() {
        String spadeCard;
        if (this.getSpades() == 1) {
            spadeCard = "AS";
        }
        else if (this.getSpades() == 11) {
            spadeCard = "JS";
        }
        else if (this.getSpades() == 12) {
            spadeCard = "QS";
        }
        else if (this.getSpades() == 13) {
            spadeCard = "KS";
        }
        else {
            spadeCard = this.getSpades() + "S";
        }
        return spadeCard;
    }

    public String getHeartCard() {
        String heartCard;
        if (this.getHearts() == 1) {
            heartCard = "AH";
        }
        else if (this.getHearts() == 11) {
            heartCard = "JH";
        }
        else if (this.getHearts() == 12) {
            heartCard = "QH";
        }
        else if (this.getHearts() == 13) {
            heartCard = "KH";
        }
        else {
            heartCard = this.getHearts() + "H";
        }
        return heartCard;
    }

    public String getClubCard() {
        String clubCard;
        if (this.getClubs() == 1) {
            clubCard = "AC";
        }
        else if (this.getClubs() == 11) {
            clubCard = "JC";
        }
        else if (this.getClubs() == 12) {
            clubCard = "QC";
        }
        else if (this.getClubs() == 13) {
            clubCard = "KC";
        }
        else {
            clubCard = this.getClubs() + "C";
        }
        return clubCard;
    }

    public String getDiamondCard() {
        String diamondCard;
        if (this.getDiamonds() == 1) {
            diamondCard = "AD";
        }
        else if (this.getDiamonds() == 11) {
            diamondCard = "JD";
        }
        else if (this.getDiamonds() == 12) {
            diamondCard = "QD";
        }
        else if (this.getDiamonds() == 13) {
            diamondCard = "KD";
        }
        else {
            diamondCard = this.getDiamonds() + "D";
        }
        return diamondCard;
    }
}
